Fix caller for loggers created WithName or WithValues
go-logr/zapr pull request #14
Opened 2019-12-19 19:15 UTC by magicmoose

AddCallerSkip Is only needed on new loggers. 
Adding additional skips on calling WithName breaks the caller info

fixes #13

2020-05-29 17:10 UTC, thockin commented
@DirectXMan12

2020-06-01 23:05 UTC, DirectXMan12 requested changes
minor nit, otherwise good

2020-06-01 23:05 UTC, DirectXMan12 commented on zapr.go
> +func internalNewLogger(l *zap.Logger, callerSkip int) logr.Logger {
nit: call this `newLoggerWithExtraSkip` or something descriptive

2020-06-01 23:06 UTC, DirectXMan12 commented
oh, shoot, I'm sorry for how long this took to notice.  If you're still around and willing to fix the nit, that's great, otherwise I'll fix and merge in a day or two.

2020-06-02 11:48 UTC, magicmoose commented
Changed the name to newLoggerWithExtraSkip

2020-06-11 00:38 UTC, merged